/** Central mutable application state */
export const store = {
  canvas: null,
  ctx: null,
  rc: null,
  vp: { x: 0, y: 0, zoom: 1 },
  shapes: [],
  selectedIds: new Set(),
  currentTool: 'select',
  dirty: true,
  isDrawing: false,
  drawStart: null,
  currentShape: null,
  pencilPoints: [],
  isDragging: false,
  dragStartPos: null,
  dragStartShapePositions: {},
  dragMode: null,
  resizeTarget: null,
  isRubberBand: false,
  rubberBand: null,
  isPanning: false,
  panStart: null,
  spaceDown: false,
  arrowSnapPoint: null,
  snapLines: [],
  editingShapeId: null,
  styleDefaults: {
    strokeColor: '#1e1e1e',
    fillColor: '#ffffff',
    strokeWidth: 1,
    roughness: 1,
    fontSize: 24,
    fontFamily: 'Caveat',
    textAlign: 'left',
    opacity: 1,
    strokeStyle: 'solid',
    fillStyle: 'solid',
  },
  documentTitle: 'Untitled',
  backgroundColor: '#f8f9fa',
  resizeGroupOrig: null,
  _pointerActive: false,
  history: [],
  historyIndex: -1,
  ctxMenuShapeId: null,
  clipboard: null,
  _lastSelectionSig: '',
};

export function markDirty() {
  store.dirty = true;
}
